#-------------------------------------------------------
# Options to cicconf
#-------------------------------------------------------
options:
  template:
    ip: tech_sky130B/cicconf/ip_template.yaml
  project: rply
  technology: sky130nm

cicsim:
  remote: git@github.com:wulffern/cicsim.git
  revision: main
  on_clone: python3 -m pip install --user -e .
cicpy:
  remote: git@github.com:wulffern/cicpy.git
  revision: master
  on_clone: python3 -m pip install --user -e .

#-------------------------------------------------------
# TECHs
#-------------------------------------------------------
cpdk:
  remote: git@github.com:wulffern/cpdk.git
  revision: main
tech_sky130A:
  remote: git@github.com:wulffern/tech_sky130A.git
  revision: main
tech_sky130B:
  remote: git@github.com:wulffern/tech_sky130B.git
  revision: main

#-------------------------------------------------------
# SUN (2022)
# "It's not you, it's me, I don't like you." – Ayrun Sun, Farscape
#-------------------------------------------------------
sun_pll_sky130nm:
  remote: git@github.com:wulffern/sun_pll_sky130nm.git
  revision: main
sun_tr_sky130nm:
  remote: git@github.com:wulffern/sun_tr_sky130nm.git
  revision: main
sun_trb_sky130nm:
  remote: git@github.com:wulffern/sun_trb_sky130nm.git
  revision: main
sun_sar9b_sky130nm:
  remote: git@github.com:wulffern/sun_sar9b_sky130nm.git
  revision: main


#-------------------------------------------------------
# RPLY (2023)
#"I say we take off and nuke the site from orbit.
# It's the only way to be sure.", Ellen Ripley, Aliens
#-------------------------------------------------------
rply_bias_sky130nm:
  remote: git@github.com:wulffern/rply_bias_sky130nm.git
  revision: main
rply_temp_sky130nm:
  remote: git@github.com:wulffern/rply_bias_sky130nm.git
  revision: main
