name: aicex ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - name: aicex
        uses: actions/checkout@main
        with:
          submodules: true
      - name: Install eda
        run: |
          sudo source tests/install_ubuntu.sh
          source tests/install_cicsim.sh
          source tests/install_cicpy.sh
      - name: Run test
        run:  |
          source tests/run_tests.sh
