name: aicex ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    container: wulffern/aicex:latest
    steps:
      - name: aicex
        uses: actions/checkout@main
      - name: Run tests
        run: |
          /bin/bash tests/run_docker_test.sh
